apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-wordpress
spec:
  selector:
    matchLabels:
      app: nginx-wordpress
  replicas: 3 # tells deployment to run 2 pods matching the template
  serviceName: nginx-wordpress
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nginx-wordpress
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: nginx-wordpress
          image: phanikumary1995/nginx-wordpress-eks
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
            - name: https
              containerPort: 443
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 20
